saddle-finance/saddle-frontend

src/components/DepositPage.tsx, src/components/WithdrawPage.tsx
Previous formatting didn't shift decimals when formatting as percentage.
=> Fix Slippage % Display

src/hooks/usePoolData.ts, src/pages/DepositBTC.tsx
Currently we check: 1) if pool cap is already met exactly 2) if pending deposit will exceed user cap.
This PR adds some wiggle room to the pool cap check since it will never be met *exactly*, and also checks pending deposits against the pool cap.
=> Check pending deposit against pool cap as well as user cap

src/utils/__tests__/priceImpact.ts, src/utils/priceImpact.ts
Per a conversation with @alphastorm , lower the threshold for a priceimpact warning from 10% -> 1%
=> Change price impact threshold to 1%

src/components/DeadlineField.tsx, src/components/DepositPage.tsx, src/components/GasField.tsx, src/components/ReviewDeposit.tsx, src/components/ReviewSwap.tsx, src/components/ReviewWithdraw.tsx, src/components/SlippageField.tsx, src/hooks/useApproveAndDeposit.ts, src/hooks/useApproveAndSwap.ts, src/hooks/useApproveAndWithdraw.ts, src/pages/DepositBTC.tsx, src/pages/SwapBTC.tsx, src/pages/WithdrawBTC.tsx, src/state/index.ts, src/state/user.ts, src/utils/index.ts
See [slack](https://saddle-finance.slack.com/archives/C017XJU4GSJ/p1614222819021900) for issue details.
We were incorrectly merging static `initialState` with state pulled from `localStorage` while hydrating redux. As a result, some users did not have a `transactionDeadline`, which consequently caused their transactions to fail (before even reaching the contract, so no gas was spent). 
This PR does 3 things in order of importance:
1) Corrects how `initialState` is merged into localstorage state in redux
2) Adjusts the implementation of `deadlines` to match that of `slippage` and `gas` (eg using `selected` and `custom` states) which also fixes a minor bug (type 10 or 30 into the custom deadline field in prod to see)
3) Moves Deadlines, gas, and slippage from props to being accessed from …
=> Correct deadline loading logic

src/constants/index.ts, src/hooks/useApproveAndDeposit.ts, src/hooks/useApproveAndWithdraw.ts, src/hooks/useContract.ts, src/hooks/usePoolData.ts, src/hooks/useWithdrawFormState.ts, src/pages/App.tsx, src/pages/Deposit.tsx, src/pages/Swap.tsx, src/pages/Withdraw.tsx, src/state/wallet/hooks.ts
Remove hardcoded poolnames from top level pages, replace with `poolName` prop. Check `App.tsx` for how this is used.
Tested and working locally on a branch of the contract repo before some recent changes to the local environment.
=> Make existing pages generic w/ poolName prop

src/components/PoolOverview.tsx, src/hooks/usePoolData.ts, src/pages/App.tsx
Since we're unable to interact with contracts when the user is not connected to a wallet, just show 0 values for everything to give a less broken experience. Additionally, display the "connect wallet" modal on every page until the user connects a wallet.
=> Zero values instead of contract data when no user wallet connected

src/hooks/useApproveAndDeposit.ts
Since MetaMask has fixed the issue with their v.9.2.1 release (13 days ago), we should change the approvals back to concurrent ones for a better UX.
https://github.com/MetaMask/metamask-extension/releases/tag/v9.2.1
=> Change the sequential approvals to concurrent ones

src/connectors/index.ts, src/hooks/usePoolData.ts, src/index.tsx, src/pages/App.tsx
- switch from web3provider to getDefaultProvider, which appears to fix the malformed rpc requests
- turn off "no wallet connected" modals
=> Fix missing pool data when no wallet connected

src/constants/index.ts
Contract addresses were updated with https://github.com/saddle-finance/saddle-contract/pull/357
With the above PR (deploying libraries from a separate account), frontend-relevant contract addresses should stay the same even after deploying new libraries / auxiliary contracts.
=> Update contract addresses

src/state/wallet/hooks.ts, src/types/ethcall.d.ts
Create an internal type for the `ethcall` library (TS doesn't let you overwrite existing declarations, otherwise I would have declared this type on the library directly) which infers the return type of calls from the `typechain` contract types.
=> Add types for ethcall

src/constants/index.ts, src/hooks/__tests__/useCalculateSwapPairs.ts, src/hooks/useCalculateSwapPairs.ts, src/utils/__tests__/index.ts, src/utils/index.ts
This PR creates the initial logic for calculating if and how one token can be swapped with another. The swap types are as follows:
```
export enum SWAP_TYPES {
DIRECT, // route length 2
SYNTH_TO_SYNTH, // route length 2
SYNTH_TO_TOKEN, // route length 3
TOKEN_TO_SYNTH, // route length 3
TOKEN_TO_TOKEN, // route length 4
INVALID,
}
```
This function also returns the route for display, as well as some data that will be required for contract calls (pool, token index, etc)
=> Calculate Swap Pairs

src/components/DepositPage.tsx, src/components/PoolOverview.tsx, src/constants/abis/sharedStakeStakingRewards.json, src/hooks/usePoolData.ts, src/pages/App.tsx, src/state/wallet/hooks.ts, src/types/ethcall.d.ts, src/utils/updateTokenPrices.ts
- Calculate veth2 price from the ex-rate between veths & eth. 
- Add sgt pool apy in `usePoolData` hook. 
- Display new apy. 
- Nest tokenPrices under react manager so that the token price calculations have access to a web3 provider
NOTE: Our apy is slightly different from what is shown on the SGT website. I think this a bug in [their code](https://github.com/SharedStake/SharedStake-ui/blob/main/src/utils/veth2.js) where they calculate the veth2 price by calling `swap.calculateSwap(0,1)` which is eth -> weth2, when what I think they want is `(1,0)`. But somebody please double check my math on this as I am no mathlete.
=> SharedStake APY

cypress/integration/deposit.test.ts, src/components/SearchSelect.module.scss, src/components/SearchSelect.tsx, src/components/SwapInput.tsx, src/components/SwapPage.tsx, src/constants/index.ts, src/hooks/useApproveAndSwap.ts, src/hooks/useCalculateSwapPairs.ts, src/pages/Swap.tsx
This PR contains major logic changes that enable Virtual Swaps and calculating swaps. 
This includes removing the `activePool` logic which has been superseded by the `calculateSwapPairs` logic in the swap page. This also adds a couple VS-related fields to the swap form state which come from `calculateSwapPairs` - this includes `poolName, tokenIndex, and swapType`. The txn gas estimate is also updated with real costs for virtual swaps. Finally, this includes a minor logic change of using `tokenPriceUSD` for calculating the price impact of swaps rather than token amount, and also removes the incorrect use of virtualprice when calculating swap price impact. 
To test this locally:
- checkout [this branch](https://github.com/saddle-finance/saddle-frontend/pull/474) of the frontend repo which …
=> [VS pt 2] Virtual Swaps & calcSwaps

src/components/SwapPage.scss, src/components/SwapPage.tsx, src/constants/index.ts, src/hooks/usePendingSwapData.ts, src/pages/App.tsx, src/pages/Swap.tsx, src/providers/PendingSwapsProvider.tsx, src/utils/__tests__/index.ts, src/utils/index.ts
Creates `usePendingSwapData.ts` hook which fetches existing virtual swaps from event logs on mount, and also attaches listeners for new virtual swap actions. Also adds the basic UI of showing that there are pendingSwaps.
=> Fetch Pending Swaps

src/constants/abis/swapFlashLoanNoWithdrawFee.json
This adds a new json file to the repo. 
Frontend should be updated to have some kind of logic to tell which addresses are using which ABI.
```
BTCPool - swapGuarded
USDPool - swapFlashLoan
vETH2Pool - swapFlashLoan
Future pools should use `swapFlashLoanNoWithdrawFee`
```
```
BTCPool - swapGuarded
USDPool - swapFlashLoanNoWithdrawFee
vETH2Pool - swapFlashLoanNoWithdrawFee
Future pools should use `swapFlashLoanNoWithdrawFee`
```
=> Add a new ABI that has no witdraw fee features

public/locales/en.json, public/locales/zh.json, src/components/PoolInfoCard.tsx, src/components/PoolOverview.tsx, src/hooks/usePoolData.ts, src/pages/App.tsx, src/state/application.ts, src/utils/__tests__/index.ts, src/utils/getSwapStats.ts, src/utils/index.ts
Pull in swap stats from json API, add to redux state, thread through to UI. Add new short format option for bigNumbers. 
Note: We'll need to add both the alUSD pool and the 4pool to the graph for this to be useful across the board
=> Display native pool APY and 24h volume on the pools page

src/hooks/__tests__/useCalculateSwapPairs.ts, src/hooks/useCalculateSwapPairs.ts, src/hooks/usePoolsTVL.ts
1) guesstimate each pool's tvl in bulk using multicall in `usePoolsTVL`
2) pass this to `useCalculateSwapPairs` where it is used to sort pools in various places so that the highest tvl pool is listed first
This is kind of a patch job and in the future I'd like a cleaner, more central way of grabbing all pool info in bulk rather than having a hook for each pool.
=> Sort swap orders by pool TVL

src/pages/Deposit.tsx
When adding the concept to "underlying tokens", the frontend was accidentally counting one token twice (in this case susd since it was both a `token` and `underlying token`)
Resolves #574
=> Fix Deposit logic double-counting a token

src/pages/App.tsx
Since 1559 should be backwards compatible, maybe the baseFee is just changing faster than we're polling. Increase speed to test this idea.
=> Poll gas every 5s

src/pages/App.tsx, src/utils/notifyHandler.ts
Passing valid `dappId` or `networkId` config will trigger notify to look for both configs.
This commit changes so when using unsupported networks, we dont pass either configs.
=> Allow notify to be run on unsupported chains

src/pages/Swap.tsx
There was an imprecise type which caused the frontend to crash if a user selected "To" before "from" in the swap interface - this PR addresses that type issue
=> Fix error on selecting Swap To before From

src/components/DepositPage.scss, src/components/DepositPage.tsx, src/components/WithdrawPage.scss, src/components/WithdrawPage.tsx
The bonus for deposits was accidentally hidden after deleting a class when consolidating the Advanced Options component. This PR fixes the UI and shows the bonus again.
=> Fix hidden deposit bonus

.eslintrc, src/hooks/useAddTokenToMetamask.ts
Implement hook to add Token to MetaMask. This hook is generic for any `Token` obj.
I've left out the `image` parameter for now
As there's no UI element currently using this functionality, I tested manually by adding a dummy button & couple of tokens (`STABLECOIN_SWAP_TOKEN` and `TBTC_SWAP_TOKEN`)
The `.eslintrc` is for the `@ts-ignore` that we need as ethers returns an incorrect type
=> Implement hook to add token to metamask

src/pages/Withdraw.tsx, src/utils/__tests__/priceImpact.ts, src/utils/priceImpact.ts
Previously we were doing `(VP * output) / input - 1` for both deposits and withdraws. Now we still use that for deposits but instead use `output / (input * VP) - 1` for withdraws since the input is an lpToken
=> Correct price impact math for withdraws

src/components/PoolOverview.scss, src/components/PoolOverview.tsx, src/components/SearchSelect.module.scss, src/components/SearchSelect.tsx, src/components/Tag.module.scss, src/components/Tag.tsx
Currently both SearchSelect and PoolOverview uses tags with local styling. We may use tag in other components in the future as well. So it's worth to have Tag to be a component. 
* Create Tag component
* Migrate SearchSelect and PoolOverview tags with Tag component
Vlose #588
=> Create Tag component for SearchSelect and PoolOverview

src/components/AdvancedOptions.tsx, src/components/PendingSwapModal.tsx, src/hooks/useApproveAndDeposit.ts, src/hooks/useApproveAndMigrateUSD.ts, src/hooks/useApproveAndSwap.ts, src/hooks/useApproveAndWithdraw.ts, src/utils/checkAndApproveTokenForTrade.ts, src/utils/updateGasPrices.ts
Gas fetching seems to be broken, which breaks transactions. We aim to remove gas fetching and setting, instead relying on the user's wallet to set gas. This is what Uniswap does.
- noops the fetching of gasprice from the network
- hides gasprice from advanced options
- removes gasprice from all contract interactions (please double check)
NOTE - gas data is still shown in the txn review modals, these should be removed as well for completion
=> first pass at removing gas

src/components/TopMenu.tsx
Simply hide the SDL button in the nav on non-hardhat / mainnet networks
#737 
19f045ff9f90.png)
=> Hide SDL reward button on non-hardhat / mainnet networks

src/hooks/useCalculateSwapPairs.ts, src/hooks/usePoolsStatuses.ts, src/pages/Swap.tsx
- get `paused` status for all pools via multicall (eventually to be replaced by graph)
- use paused status to remove tokens from swap UI
- use paused status to remove pools from swap route calculation
=> Account for paused status when getting swap pairs

src/hooks/usePoolData.ts
We were previously trying to get APYs from the `pool-stats` response using the MetaSwapDeposit address rather than just the swap address.
After
Before
=> use correct pool address when getting meta pool apys

src/utils/thirdPartyIntegrations.ts
New rewards contract is https://etherscan.io/address/0xb4c35747c26e4ab5f1a7cdc7e875b5946efa6fa9#code as per https://www.tbtcfarm.info/pool/saddle_v2_migrate/
See that the math is the same:
resolves #786
=> Migrate keep rewards to tbtcv2 metapool

src/providers/RewardsBalancesProvider.tsx
Fixes bug where retro balance was correctly null, but was not set at 0 in the provider.
=> Fix retro balance bug

src/components/SwapPage.tsx
There is a spacing under the bottom of  `swap` page.
This is appearing on small screen which the screen height is less than the height of  swap form .
=> Fix: layout fix on small screen

cypress/integration/deposit.test.ts, public/locales/en.json, src/components/MyShareCard.tsx
Test was flakey. Removed wait() calls and non-essential loop logic. Now test will make a standard deposit, then assert toast renders with successful deposit message, then assert that one of the token values updates which indicates the deposit did indeed go through the flow successfully.
subtle UI format bug fix thrown in as well.
=> simplified Deposit e2e flow, asserting tx succ and value change

src/constants/index.ts, src/utils/migrations.ts, src/utils/minichef.ts
The first of several steps to remove logic from usePoolData and separate concerns into their own files. Notice I'm also moving from poolname to address
=> Break minichef and migrations out to their own fns

src/components/GaugeWeight.tsx, src/constants/index.ts, src/pages/VeSDL/GaugeVote.tsx
- Add dark background color on highchart
- Center circluar loading for GaugeVote.
https://github.com/saddle-finance/saddle-frontend/issues/1004
close: https://github.com/saddle-finance/saddle-frontend/issues/1004
=> Add dark mode on highchart and center Circular progress

src/components/PoolInfoCard.tsx, src/components/Toastify.tsx, src/utils/getEtherscanLink.ts
It's quite difficult to find the `token contracts` associated with a `pool`, especially the `LP token`.
This PR adds the token contract and LP token conract address on `PoolInfoCard` component.
https://www.figma.com/file/Aa3IfDUO68aCNr8nZTuQ8S/Product-Design-with-MUI?node-id=762%3A32576
https://saddle-finance.slack.com/archives/C019X395350/p1650985929086549
closes: https://github.com/saddle-finance/saddle-frontend/issues/811
=> Add pool contract address information on PoolInfoCard

cypress/integration/withdrawal.test.ts, src/components/WithdrawPage.tsx, src/constants/index.ts, src/hooks/useApproveAndWithdraw.ts, src/hooks/useContract.ts, src/hooks/usePoolData.ts, src/hooks/useWithdrawFormState.ts, src/pages/App.tsx, src/pages/Withdraw.tsx, src/utils/__tests__/index.ts
As part of the ongoing move from constants to Registry, this PR removes references to `POOLS_MAP`, `TOKENS_MAP`, and `PoolName` from the withdraw flow. Token symbols are also replaced with token addresses.
***IMPORTANT***: For reviewers, please verify any new/migrated contract addresses thoroughly. 
Fixes # (Add link to github issue if available)
_Note_: If merged/deployed alone, make that known in a public Slack channel and ping team members. If the description above is clear and concise, it should be sufficient for team members with minimal context to verify the work that was done. Otherwise, please revise and provide additional information.
=> Remove POOLS_MAP from withdraw flow, replaces symbols with addresses

src/pages/App.tsx, src/pages/VeSDL/GaugeVote.tsx, src/providers/GaugeProvider.tsx, src/state/index.ts, src/state/voteEscrowSnapshots.ts, src/utils/__tests__/index.ts, src/utils/getSnapshotVoteData.ts, src/utils/index.ts
***Description:*** As part of the veSDL Gauge component page, there will be a table with links to the snapshot voting underneath the PieChart. It will have the voting period as the title and a button that links to the snapshot voting page. The data is fetched from the Snapshot GraphQL API and added to a key in the redux store that is rendered only once on page load. 
*Notes*:
- Only 10 entries are rendered, but can be changed if need be. 
- GraphQL calls only are getting the `id, title, start, state`. Can add extra fields later if needed
- If the state of the snapshot voting is still ongoing, the Button will show up as `vote`.
- If the state of the snapshot voting is closed, the Button will show up as `results`.
- The `View all votes` links to …
=> Add Snapshot voting links to veSDL page

src/constants/abis/helperContract.json, src/constants/index.ts, src/providers/GaugeProvider.tsx, src/providers/TokensProvider.tsx
Adds gauge rewards to the gauge provider, as well as including them in the tokens provider for fetching token info.
To test locally, start your local evm, then run `npx hardhat run scripts/checkGaugeRewards.ts --network localhost` to create rewards 
@ug02fast
=> Add Gauge Rewards

src/constants/index.ts
Metapools were missing minichef pids for SDL rewards.
=> Adding missed minichef pids to new metapools

src/types/ethcall.d.ts, src/utils/migrations.ts, src/utils/minichef.ts, src/utils/thirdPartyIntegrations.ts
Before: 
```
const foo = await multicallProvider.tryEach([getName], [false]) // type: [string]
const foo = await multicallProvider.tryEach([getName], [true]) // also type: [string]
```
After: 
```
const foo = await multicallProvider.tryEach([getName], [false]) // type: [string]
const foo = await multicallProvider.tryEach([getName], [true]) //  type: [string | null]
```
Closes #1045
=> Add correct ethcall tryEach types based on canFail

cypress/integration/deposit.test.ts
add 10 minutes to evm time after basepool deposit to bust metapool cache
https://saddle-finance.slack.com/archives/C017XJU4GSJ/p1653459974141809?thread_ts=1653355453.867859&cid=C017XJU4GSJ
=> fix for metaswap tests

scripts/unpauseEvmos.js, src/components/GaugeWeight.tsx, src/components/TokenClaimDialog.tsx, src/components/Transactions.tsx, src/hooks/useCalculateSwapPairs.ts, src/pages/Pools.tsx, src/providers/MinichefProvider.tsx, src/providers/RewardsBalancesProvider.tsx, src/providers/TokensProvider.tsx, src/providers/UserStateProvider.tsx, src/react-app-env.d.ts
key: value mappings should be correctly defined as `{[key: string]: value | undefined}` since `map[anyKey]` is not guaranteed to be defined. 
However, this can be annoying when using `Object.values` since it'll think the value may be undefined, when we know that's not the case. Update the type for `Object.values` to never be undefined (may still be null)
=> Use better type for Object.values for maybe undefined values

src/components/DepositPage.tsx, src/components/MyFarm.tsx, src/constants/abis/genericToken.json, src/constants/index.ts, src/hooks/useContract.ts, src/pages/VeSDL/LockedInfo.tsx, src/pages/VestingClaim.tsx, src/utils/checkAndApproveTokenForTrade.ts
Add veSDL data to gauge page
Cleanup:
- move `veSDLFeatureReady` to global constant
- introduce `GenericToken` abi for basic tasks like approvals
- change `useSdlContract` type to `Sdl`
=> Add veSDL data

src/pages/Withdraw.tsx
Preventing the white page when withdraw
To withdraw token, when user input the percent on the withdraw page, it appears white screen.
Because LP token don't have price(it is having undefined), and it make invalide input on `commify` function. That was the reason of blank screen.
=> Fix Withdraw issue

src/pages/VeSDL/index.tsx
Disable to choose unlock date  other than Tuursday.
closes: https://github.com/saddle-finance/saddle-frontend/issues/1067
=> Disable unlock date other than Tuesday

src/components/DepositPage.tsx, src/components/GaugeWeight.tsx, src/components/TokenClaimDialog.tsx, src/hooks/usePoolData.ts, src/pages/VeSDL/GaugeVote.tsx, src/pages/VeSDL/VeTokenCalculator.tsx, src/providers/AprsProvider.tsx, src/providers/TokensProvider.tsx, src/providers/UserStateProvider.tsx, src/utils/gauges.ts, src/utils/updateSdlWethSushiInfo.ts
Move gauges from being keyed on poolAddress to lpTokenAddress, since our gauges now also support the sdl/weth sushi lp token.
gaugeAprs are now keyed on gaugeAddress instead of poolAddress so that APRs for all gauges are calculated. 
TODO - we have the assetPrice for pools, but we should figure out how to get that for the sushi pair
=> Key gauges by lpToken address

src/components/TopMenu.tsx, src/constants/index.ts, src/utils/updateTokenPrices.ts
***Description***: This is to add a button at the top Menu nav bar to include a SDL price tracker. SDL price information will render once CoinGecko starts to return a value for the SDL token. This work also include updating the geckoId of SDL token from `saddle-dao` to `saddle-finance`
#1103
=> Add SDL icon & price to header

src/pages/Farm/ClaimRewardsDlg.tsx, src/pages/Farm/StakeDialog.tsx, src/utils/index.ts
Log when a stake/unstake fails, hide empty lp balance from the reward claim screen
Resolves #1124 #1125
=> better logging, hide empty lp

public/locales/en.json, src/components/TokenClaimDialog.tsx
This will render minichef "outdated" lp rewards for the user to claim if there are pools with rewards to claim. This was not accounted for initially.
=> Allow claiming of minichef rewards in token dialog

src/hooks/useUserGauge.ts, src/pages/Farm/StakeDialog.tsx
***Description***: On the staking dialog modal, user's current boost multiplier will be calculated and displayed. If the user hasn't provided LP or staked any asset, the multiplier will show up as `-`
=> Display boost multiplier on StakingDialog modal

src/components/TokenClaimDialog.tsx
***Description***: Since SDL now exists on side chains, rewards contract no longer needs to call .deposit() with amount Zero on non-Mainnet networks. Now, we can call .harvest() directly.
=> Patch to claim tokens on side chains

src/hooks/useUserGauge.ts, src/pages/Farm/StakeDialog.tsx, src/pages/VeSDL/VeTokenCalculator.tsx, src/utils/index.ts
- Boost math
Boost  logic is based on the following logic.
```
(min((userLiquidity*40/100) + TotalLiquidity*UserVeSdlBalance/TotalVeSdlBalance*(100-40)/100 , UserLiquidity)) / (UserLiquidity*40/100)
```
- UserVeSdlBalance = 0
Then boost = (min(UserLiquidity*40/100, UserLiquidity) / (UserLiquidity*40/100) = 1.0
- UserVeSdlBalance = TotalVeSdlBalance
Then `TotalLiquidity*UserVeSdlBalance/TotalVeSdlBalance*(100-40)/100` will be `TotalLiquidity*(100-40)/100` .
numerator will be UserLiquidity.
So, boost = UserLiquidity/(UserLiquidity * 40 /100) = 2.5,  this is max value of the bost.
- veSDL for max boost
When `userLiquidity*40/100) + TotalLiquidity*UserVeSdlBalance/TotalVeSdlBalance*(100-40)/100` === `UserLiquidity`, user can have max boost under user's Liquidity.
In this case, …
=> Fix boost math and decimal

src/components/TopMenu.tsx, src/hooks/useContract.ts
For some reason, the codebase had issues fetching information about the SLP pair, causing the TVL of the pair not to render. This was resolved by remove the reference to account from `useSdlWethSushiPairContract`. I removed it from a few other places as well for good housekeeping.
I also update the sushi link from the analytics page to https://ethereum.sushi.com/swap?inputCurrency=ETH&outputCurrency=0xf1Dc500FdE233A4055e25e5BbF516372BC4F6871
=> Fix SLP fetching issue

src/components/TokenClaimDialog.tsx, src/utils/gauges.ts
Now explicitly check that that we have minter rewards before creating minter txn, check that we have gauge rewards before creating gauge claim txn. Give more explicit feedback to user.
=> Fix gauge rewards claiming logic

src/constants/networks.ts, src/utils/getEtherscanLink.ts
The link was for Kava needs a special case for links to contracts that's different from the other networks.
Hexlify function doesn't seem to play nicely anymore.
kava testnet rpc url needs updating.
added the potential coingecko platform id
=> fixed multiscan link for kava and potential coingecko id

src/constants/index.ts
Because of wrong `coingecko id` of `USX` `updateTokenPrice` doesn't fetch the price of USX from coingecko.
We can check coingecko id from `coingecko api` (https://api.coingecko.com/api/v3/coins/list)
=> Fix Coingecko id of USX token

src/pages/App.tsx
Directly linking to a `/pools/:route/:action` triggered redirect before pools load. This forces Redirect to wait before triggering.
=> Wait for basicPools to load before triggering redirect

src/pages/VeSDL/index.tsx, src/utils/index.ts
***Description:*** Upon the `date-fns` package update from 2.25 -> 2.29, `intervalToDuration` method will throw a RangeError if the end date is before the start date. This PR addresses that issue by finding the appropriate max and min between the `proposeUnlockDate` and `lockEnd` values and passing that into the `intervalToDuration` accordingly.
=> Date Picker alternative patch

src/utils/index.ts
The reference to `isLegacyPool` seems to be `isMigrated` now. This was preventing withdraws from legacy pools.
=> isMigrated added to condition

src/providers/UserStateProvider.tsx
there's a bug with some logic mapping causing swap input to crash on token selection when this change in place. I still don't know the root cause but this unblocks Swap for now.
=> Revert not storing Zero values

src/components/DepositPage.tsx, src/hooks/useApproveAndDeposit.ts
check isMetaSwap when deciding whether to allowed for wrapped deposits and revert useTokens to TokenContext as there's a problem with waiting for basicPools to initialize in the query
=> unable to load swap bug - check isMetaSwap and revert useTokens to TokenContext

src/components/PoolOverview.tsx, src/hooks/usePoolData.ts, src/providers/MinichefProvider.tsx, src/providers/UserStateProvider.tsx, src/utils/minichef.ts
- update `utils/minichef` to calculate the amount of lpToken staked in minichef for each pool
- update `usePoolData` to calculate minichef apr from amount staked, tvl, and sdl price
- update `PoolOverview` to display apr
=> Display minichef APRs

src/components/AccountDetails.tsx, src/components/Dialog.tsx
On iOS mobile, user can’t close “Account” menu and overlapping text. 
Reported from [discord](https://discord.com/channels/780508954916290610/780521388959727627/1022581326571909191).
- Increased the zIndex of close icon button of Dialog
- Changed the layout for `Change account` button.
=> Fix breaking of change account text

src/components/TokenClaimDialog.tsx, src/utils/gauges.ts
***Description***: In the case of when a user has SDL/Minter rewards for a gauge that previously has a non-Zero SDL rate and currently has a Zero rate value, the sdlReward does not get added to the gauge rewards attribute due to the Zero SDL rate check.
***Solution***: Removed the sdlRate check when concating the rewards lists and allow ClaimTokenDialog to handle showing/hiding gauge rewards depending on rewards balance rather than sdlRate
=> TokenClaimDialog rewards patch

src/components/GaugeWeight.tsx, src/constants/abis/gaugeController.json, src/hooks/useSidechainGaugeWeightDataOnMainnet.ts, src/pages/VeSDL/OnChainVote.tsx, src/utils/gauges.ts
Changes to support correct operation of sidechain gauges:
- Use '_write' fn when fetching gauges data
- Update controller abi to view
- Format gauge names to include chain name (for sidechains)
- Include sidechain root gauges in voting options
=> Use '_write' fn for gauges data, update controller abi to view, format gauge names

src/components/TopMenu.tsx, src/constants/index.ts, src/utils/gauges.ts
- engage `IS_CROSS_CHAIN_GAUGES_LIVE` flag
- add Opt and Arb to chains that should display gauges
- only show vesdl on mainnet
=> Turn on x-chain gauges

src/hooks/useSwapStats.ts
The `swap-stats` endpoint returns json which includes the unix timestamp of when it was created. This PR compares the timestamp to the current time and fires a sentry message when the response is more than a day old
=> Log when swap stats is out of date

src/hooks/useRedirectInvalidPool.ts, src/pages/Deposit.tsx, src/pages/Withdraw.tsx
Automatically redirect abuses of the route wildcard in `/pools/:poolName/deposit` to `/pools`. Eg `pools/click_here/deposit` does not match a real pool name and will be redirected
=> Redirect misnamed pools

src/hooks/useApproveAndWithdraw.ts, src/hooks/useWithdrawFormState.ts, src/pages/Withdraw.tsx
This fixes two issues:
- the output of `calculateRemoveLiquidityOneToken` was being used as an input instead of an LP Token amount
- `calculateTokenAmount` was being called on a MetaSwapDeposit contract even when the user was withdrawing wrapped, but it should have been on the MetaSwap contract instead
=> Fix single token withdraws from metapools

src/components/GaugeRewardsDisplay.tsx, src/components/TokenClaimDialog.tsx, src/constants/index.ts, src/providers/AprsProvider.tsx, src/utils/gauges.ts, src/utils/updateTokenPrices.ts
- handle display of reward that don't use 18 decimals
- merge rewards in the same token (eg SDL from both gauge and minter). Do this both in apr calculation, display, and claiming
-
=> multi-reward gauge improvements

src/hooks/useRegistryAddress.ts
Fetching the registry addresses were disabled on mainnet, but some logic still depended on them
=> Fix registry address dependency

.husky/_/husky.sh, src/pages/AppContainer.tsx
=> add banner for the protocol winddown
