- public/locales/en.json
- public/locales/zh-CN.json
- src/hooks/useApproveAndDeposit.ts
- src/hooks/usePoolData.ts
- src/pages/DepositBTC.tsx
- src/utils/checkAndApproveTokenForTrade.ts
> Limit deposits using the minted LP token amount instead of balance

- src/components/DepositPage.tsx
- src/components/MyActivityCard.tsx
- src/components/MyShare.tsx
- src/components/MyShareCard.tsx
- src/components/PoolInfoCard.tsx
- src/components/ReviewDeposit.tsx
- src/components/ReviewSwap.tsx
- src/components/SwapPage.tsx
- src/components/WithdrawPage.tsx
- src/hooks/usePoolData.ts
- src/pages/DepositBTC.tsx
- src/utils/index.ts
Make formatting cleaner and reduce the opportunity for mis-formatting things like percentages.
> Create BNtoString formatter

- src/components/DepositPage.tsx
- src/components/MyActivityCard.tsx
- src/components/MyShare.tsx
- src/components/MyShareCard.tsx
- src/components/PoolInfoCard.tsx
- src/pages/DepositBTC.tsx
- src/utils/index.ts
This isn't an issue now, but in the future we don't want commiified values being passed to inputs.
> Don't implicitly commify formatted BN strings

- src/hooks/usePoolData.ts
> Update KEEP incentive

- package-lock.json
- package.json
Close #153
_NB_
https://www.npmjs.com/package/node-sass
> Replace deprecated node-sass with sass

- package-lock.json
- package.json
> Remove explicit babel-loader dependency

- package-lock.json
- package.json
- src/index.tsx
- src/reportWebVitals.ts
- src/utils/googleAnalytics.ts
For more information see: https://web.dev/vitals/
Closes #278
> Setup web vitals metrics reporting

- src/index.tsx
- src/utils/googleAnalytics.ts
> Log errors to Google Analytics

- src/pages/SwapBTC.tsx
> Allow quoting without balance

- src/components/InfiniteApprovalField.scss
- src/components/InfiniteApprovalField.tsx
- src/components/SwapForm.tsx
- src/components/SwapPage.tsx
- src/components/ToolTip.scss
- src/components/ToolTip.tsx
- src/pages/SwapBTC.tsx
- src/utils/__tests__/index.ts
- src/utils/index.ts
This screenshot captures both the exchange rate, as well as the new tooltip component being used to display the full-precision value of token wallet balances.
> Swap Exchange rate, tooltip component

- .gitignore
- src/components/DeadlineField.scss
- src/components/DepositPage.scss
- src/components/GasField.scss
- src/components/Modal.scss
- src/components/MyShareCard.scss
- src/components/NoShareContent.scss
- src/components/ReviewDeposit.scss
- src/components/ReviewWithdraw.scss
- src/components/SlippageField.scss
- src/components/SwapForm.scss
- src/components/SwapPage.scss
- src/components/SwapPage.tsx
- src/components/TopMenu.scss
- src/components/Web3Status.scss
- src/components/WithdrawPage.scss
- src/pages/Risk.scss
- src/styles/viewports.scss
I'd like someone to review this to see how it looks on their end before I go ahead and submit a PR.
> Add basic mobile responsiveness

- .eslintrc
- .gitignore
- cypress.json
- cypress/integration/deposit.test.ts
- cypress/plugins/index.js
- cypress/support/commands.ts
- cypress/support/index.ts
- cypress/tsconfig.json
- package-lock.json
- package.json
- src/hooks/useApproveAndDeposit.ts
- tsconfig.json
After `npm install`ing, try it out locally using `npm run cy:open`!
> Add Cypress for integration testing

- src/components/WithdrawPage.tsx
- src/hooks/useHistoricalPoolData.ts
- src/hooks/usePoolData.ts
- src/pages/WithdrawBTC.tsx
- src/state/user.ts
- src/state/wallet/hooks.ts
- src/utils/__tests__/index.ts
- src/utils/__tests__/parseStringToBigNumber.ts
- src/utils/__tests__/priceImpact.ts
- src/utils/checkAndApproveTokenForTrade.ts
- src/utils/priceImpact.ts
We were using a mix of bignumber.from(0) and Zero from ethers constants. 
This PR makes things more consistent, and I think neater.
> use Zero from ethers constants

- .github/workflows/ci.yml
> Add coverage reporting to CI

- src/pages/App.tsx
Correct logic so the effect actually changes the `shouldShowModal` when the account is detected.
> Fix modal logic

- package-lock.json
- package.json
This PR addresses an issue with Chakra dependencies that was causing build to fail
> fix chakra dependency issue

- src/utils/updateGasPrices.ts
Resolves #425 - we now will try to fetch gas from two different sites
> Use fallback gas provider before retrying

- package-lock.json
- package.json
- src/pages/Deposit.tsx
- src/pages/Swap.tsx
- src/state/wallet/hooks.ts
- src/utils/environment.ts
https://github.com/Destiner/ethcall
https://github.com/makerdao/multicall
Closes #391
When running this locally make sure that your `.env.local` is set to:
```
REACT_APP_NETWORK_URL="http://127.0.0.1:8545/"
```
> Use ethcall and Multicall to load pool token balances

- src/constants/index.ts
https://github.com/saddle-finance/saddle-contract/pull/401
Above PR will change some of the contract addresses (USD pool and vETH2 pool) on Hardhat. This PR updates them.
> Update contract addresses on hardhat

- public/locales/en.json
- public/locales/zh.json
- src/components/PoolInfoCard.scss
- src/components/PoolInfoCard.tsx
- src/hooks/usePoolData.ts
> Add info about A param

- package-lock.json
- src/components/Button.scss
Fix UI bug: Remove the button shadow of PoolOverview
Close #499
> Remove button shadow

- src/components/Button.scss
- src/components/Modal.scss
- src/components/SwapInput.module.scss
- src/components/SwapInput.tsx
- src/components/SwapPage.scss
- src/constants/index.ts
- src/hooks/__tests__/useCalculateSwapPairs.ts
- src/pages/Swap.tsx
- src/utils/dateTime.ts
- src/utils/index.ts
Just some minor changes ahead of larger PRs
> Small misc changes

- public/locales/en.json
- public/locales/zh.json
- src/components/DepositPage.tsx
- src/hooks/usePoolData.ts
- add UI for paused veth2 pool
- remove withdraw fee (incidental)
> Paused Pool UI

- src/components/MyShareCard.scss
- src/components/MyShareCard.tsx
- src/components/PoolInfoCard.tsx
- src/components/PoolOverview.tsx
- src/constants/index.ts
- src/hooks/usePoolData.ts
> Format pool figures better

- src/components/DeadlineField.tsx
- src/state/user.ts
- src/utils/index.ts
Changes the available options to 20 min and 40 min.
Sets the default placeholder for custom deadline to 20 min
Closes #513
> Update transaction deadline settings from 10,30 min to 20,40 min

- .github/workflows/ci.yml
borrowed from https://github.com/cypress-io/github-action/issues/317
documentation: https://github.com/paulmillr/chokidar
> Attempt to fix chokidar ci errors

- src/components/PoolOverview.tsx
- src/utils/thirdPartyIntegrations.ts
> Add Frax APR

- src/components/PoolOverview.scss
- src/components/PoolOverview.tsx
- src/components/ToolTip.scss
> Add tooltip to display multiple APRs

- src/hooks/useApproveAndDeposit.ts
- src/hooks/useApproveAndMigrateUSD.ts
- src/hooks/useApproveAndSwap.ts
- src/hooks/useApproveAndWithdraw.ts
- src/utils/checkAndApproveTokenForTrade.ts
> Using selected gas amount for token approval txns.

- cypress/integration/withdrawal.test.ts
Sorry for the churn here, updating with a signed commit now. This PR adds in the withdrawal flow test.
> adding withdrawal flow

- src/constants/index.ts
virtual swap flag was accidentally turned on in a previous commit, turn it off
> Turn off virtual swap

- src/connectors/index.ts
- src/index.tsx
- src/utils/getLibrary.ts
This reverts commit 5cecf7f0d1aad8dd68fc326218bc5b567b2f9f9d.
> Revert "Use getDefaultProvider in Web3ReactProvider (#598)"

- src/components/Button.scss
- src/components/Button.tsx
- src/components/NetworkDisplay.module.scss
- src/components/NetworkDisplay.tsx
- src/components/TopMenu.scss
- src/components/TopMenu.tsx
- src/connectors/index.ts
- src/constants/index.ts
- src/hooks/usePoolsTVL.ts
- src/styles/global.scss
- src/utils/index.ts
This PR creates the button which indicates the current network. A later PR will add the dropdown menu + network switching function.
> Network display button

- public/locales/en.json
- public/locales/zh.json
- src/components/TokenClaimModal.tsx
- src/providers/RewardsBalancesProvider.tsx
> Show total retro sdl

- cypress/support/commands.ts
> Fix test breaking due to the isMetaMask on the cypress/support/commands.ts

- package.json
- scripts/missing-translations.js
`npm run missing-translations -- --src=en --dst=zh`
> Add script to help find missing translations

- src/components/ReviewMigration.tsx
- src/pages/Pools.tsx
BTC based pools will show the correct currency.
On hold, waiting for the new GeneralizedMigrator contract.
> UI Fix for BTC Migrations

- src/hooks/index.ts
- src/hooks/usePoolData.ts
- src/hooks/usePoolsTVL.ts
- Now blank page is appeared  when there is no metamask.
#741
> Fix blank page when there is no metamask

- src/constants/index.ts
- src/pages/Pools.tsx
> frax-ArbUSDv2 Pool

- package-lock.json
- src/pages/VestingClaim.tsx
Hardcoded beneficiary and vesting addresses.
Dune query: https://dune.xyz/queries/281370
> Hardcode Remaining Beneficiaries

- package-lock.json
- package.json
- src/index.tsx
Close #694
Monitoring is only active in production while we're trialing it.
> Add Sentry for error and performance monitoring

- public/locales/en.json
- src/components/TokenClaimModal.module.scss
- src/components/TokenClaimModal.tsx
- src/components/WrongNetworkModal.tsx
- src/index.css
- src/styles/global.scss
- Disable claiming rewards on Arbitrum.
- Add explaining the reason of claiming.
https://github.com/saddle-finance/saddle-frontend/issues/746
https://saddle-finance.slack.com/archives/C02P1QQ1JBU/p1640182198014800
> hide retro airdrop section

- src/components/NetworkDisplay.tsx
> Change unknown to Ethereum

- src/components/TopMenu.tsx
- Fix margin  between logo and token amount.
> Margin fix on the reward button

- src/font.d.ts
- src/theme/components/CssBaseLine.ts
- Fix font import on MUI library.
https://github.com/saddle-finance/saddle-frontend/issues/791
> Fix font import 

- src/theme/palette.ts
- Update mute color from #FEA91 to #E3D899
> Update mute color

- src/components/SwapPage.tsx
> Update swap button with MUI

- public/locales/en.json
close https://github.com/saddle-finance/saddle-frontend/issues/805
> change Volumn to Vol.

- src/utils/thirdPartyIntegrations.ts
> off by one decimal in apr

- .github/workflows/ci.yml
- src/pages/Pools.module.scss
- src/pages/Pools.tsx
- src/theme/components/ButtonTheme.ts
- src/theme/index.ts
- src/theme/palette.ts
- Pool search TextField
- `CreatePool` button.
- Add breakpoint on theme.
- wrap the `PoolPage` with MUI's `Container`
https://www.figma.com/file/Aa3IfDUO68aCNr8nZTuQ8S/Product-Design-with-MUI?node-id=27%3A2852
https://github.com/saddle-finance/saddle-frontend/issues/838
> Add search pool and create permissionless pool button

- src/pages/App.tsx
Change `Toast theme` according to the `MUI` theme.
> fix: toast theme according the mui theme mode

- src/components/ReviewDeposit.tsx
> Fix: spacing fix on ReviewDepositDialgo.tsx

- src/components/PoolOverview.tsx
close: https://github.com/saddle-finance/saddle-frontend/issues/910
> Add word-break for token name

- .storybook/preview.js
- src/components/AdvancedOptions.tsx
- src/stories/ToggleButtonGroup.stories.tsx
- src/theme/components/ToggleButtonTheme.ts
- src/theme/palette.ts
- Theme update of `ToggleButtonGroup` and `ToggleButton`.
- Add `dark` theme to the component of `Storybook`
> Button group color varaition

- src/components/ReviewSwap.tsx
- src/theme/palette.ts
- Reviewswap modal has broken because I didn't consider virtualswap.
This PR is fixing the ReviewSwap Dialog for the virtual swap.
> Fix Review swap for virtual swap

- package-lock.json
- package.json
closes: https://github.com/saddle-finance/saddle-frontend/pull/946
> removed unused devDep

- src/constants/index.ts
- src/pages/Pools.tsx
- src/utils/checkAndApproveTokenForTrade.ts
- src/utils/index.ts
> Evmos mainnet FE integration.

- src/components/Toastify.tsx
- src/utils/getEtherscanLink.ts
> Support Evmos Explorer tx links.

- PULL_REQUEST_TEMPLATE/deploy.md
***Description***: Currently, there is no standardized pull request template. Going forward, please follow this format when creating a pull request because it will allow the reviewers to have a clear idea of what the changes being shipped. Also, this will be very useful in the case where we need to go back to previously closed/merged PRs to see what was changed.
> Front end pull request template

- src/components/DepositPage.tsx
- src/components/TokenInput.tsx
- src/components/WithdrawPage.tsx
- src/constants/index.ts
- src/pages/Deposit.tsx
- src/pages/VeSDL/index.tsx
- src/pages/Withdraw.tsx
Remove LPTOKEN_TO_POOL_MAP and clean up TokenInput
***IMPORTANT***: For reviewers, please verify any new/migragted contract addresses thoroughly. 
Fixes # (Add link to github issue if available)
_Note_: If merged/deployed alone, make that known in a public Slack channel and ping team members. If the description above is clear and concise, it should be sufficient for team members with minimal context to verify the work that was done. Otherwise, please revise and provide additional information.
> Remove LPTOKEN_TO_POOL_MAP and clean up TokenInput

- src/hooks/useApproveAndMigrate.ts
- src/providers/BasicPoolsProvider.tsx
- src/utils/getPoolByAddress.ts
https://github.com/saddle-finance/saddle-frontend/issues/1024
> Make better migration estimations

- .github/workflows/ci.yml
- cypress/integration/accountDetail.test.ts
- cypress/integration/advancedOption.test.ts
- cypress/integration/deposit.test.ts
- cypress/integration/swap.test.ts
- cypress/integration/topMenu.test.ts
- cypress/integration/veSdl.test.ts
- cypress/integration/withdrawal.test.ts
- cache cypress
- reduce waits
- bump github actions versions
> Other CI speed improvements

- src/components/TokenClaimDialog.tsx
- src/constants/index.ts
> Evmos Frax 3 Pool

- .github/workflows/ci.yml
- src/constants/index.ts
- src/pages/VeSDL/index.tsx
- Insert votingEscrowContract address for mainnet so that we can test after `npm run fork:mainnet`
- Fix penalty percent 
- Fix penalty Alert
> penalty percent fix

- src/i18n.ts
Current default language is "en-US". It should be "en".
This PR set default language as "en" in i18n.
> Set default lanaguage as "en"

- src/pages/VeSDL/index.tsx
closes: https://github.com/saddle-finance/saddle-frontend/issues/1082
> Fix min date

- src/components/MyFarm.tsx
Token approval check was missing prior to staking into gauge click.
> Added approval to token on stake click

- src/pages/VeSDL/index.tsx
> Hide USD price on veSDL input

- src/components/TopMenu.tsx
- src/constants/index.ts
DO NOT MERGE (before 4:30pm ET 6/23)
> Enable veSDL UI

- src/pages/VeSDL/VeTokenCalculator.tsx
- src/utils/index.ts
- no vesdl
- After locking max vesdl
> VeSDL calculator fix

- src/components/GaugeRewardsDisplay.tsx
- src/hooks/useGaugeTVL.ts
- src/pages/App.tsx
- src/pages/Farm/Farm.tsx
- src/providers/AprsProvider.tsx
- src/utils/updateTokenPrices.ts
> Add SDL price

- src/pages/Farm/Farm.tsx
- src/pages/Farm/FarmOverview.tsx
Resolve the farm page responsive issue.
closes: #1137
> Farm responsive

- src/pages/VeSDL/LockedInfo.tsx
Avg SDL lock time = (veSDL totalSupply / SDL locked in veSDL) * max lock duration
> Add sdl lock time

- public/locales/en.json
- src/components/GaugeWeight.tsx
- src/pages/VeSDL/GaugeVote.tsx
- src/pages/VeSDL/index.tsx
- Show gauges with votes down to 0.01% of total
- Commify and shorten some values
- Add missing translation
- Make buttons more uniform
> Gauge UI Improvements

- src/hooks/useApproveAndSwap.ts
removed pools_map from useApproveAndSwap
> removed pools_map from useApproveAndSwap

- src/hooks/useApproveAndDeposit.ts
Left out token selection condition.
> useApproveAndDeposit bug fix

- src/components/SiteSettingsMenu.tsx
- src/connectors/index.ts
- src/constants/index.ts
- src/constants/networks.ts
- src/utils/getEtherscanLink.ts
- src/utils/index.ts
> kava mainnet and 3pool integrated

- src/hooks/usePoolData.ts
- src/pages/App.tsx
- src/providers/ExpandedPoolsProvider.tsx
- src/utils/index.ts
- src/utils/loadable.tsx
Loadables adhere to the type 
```
export interface LoadableType<T> {
isLoading: boolean
isLoaded: boolean
isError: boolean
isSuccess: boolean
error: Error | string | null
data?: T
}
```
ExpandedPools are just like BasicPools except they are guaranteed to have all data about their tokens and underling tokens available
```
export type ExpandedPool = Omit<
BasicPool,
"tokens" | "underlyingTokens" | "lpToken"
> & {
tokens: BasicToken[]
underlyingTokens: BasicToken[]
lpToken: BasicToken
}
```
> Introduce Loadables and ExpandedPools

- src/constants/index.ts
> Minichef Reward Pids added to Arb FRAX pools.

- package-lock.json
- src/index.tsx
- src/react-app-env.d.ts
> walletconnect fix w\ Buffer

- src/components/CoinbasePayBtn.tsx
TEST FOR COINBASE PAY
https://github.com/saddle-finance/tickets/issues/319
> Add link button

- src/components/CoinbasePayBtn.tsx
> Coinbase Pay integration test

- src/components/MyFarm.tsx
This reverts commit 1eb213fa249ac4ef2e8742934d02655d9cb2286a.
Doing this because this is wrong. Will recreate.
> Revert "diff void handler call syntax"

- src/components/DepositPage.tsx
- src/components/MyFarm.tsx
- src/components/ReviewVirtualSwapSettlement.tsx
- src/pages/CreatePool/CreatePoolDialog.tsx
Fixes problem with Claim All click as well as other spots with incorrect handler call logic.
Closes: https://github.com/saddle-finance/saddle-frontend/issues/1224
> Fixes problem with Claim All click not working

- public/locales/en.json
Remove Kain, add Sam and Weston
> Update signers list on risk page

- src/pages/VeSDL/index.tsx
***Description:*** Currently, the app is using `voteEscrowContract.force_withdraw()` for all veSDL unlocking operations. This method will throw a "lock expired" error if the current timestamp is after the unlock date.
Note: Since we're not using the block timestamp, there is a 10-15 second window where the withdraw() method will throw a similar error.
> Use the correct withdraw method based on current and unlock date timestamps

- src/pages/VeSDL/index.tsx
Use `lockEnd` instead of `proposedUnlockDate` in the veSDL `unlock` UI function.
> Fix unlocking

- src/pages/App.tsx
- src/pages/Pages.tsx
- Because of lazy loading of pages, the drawer doesn't close after opening new page. so moved `TopMenu` outside of `Suspense`.
- Also created `Pages` component and moved all page import to that component.
https://user-images.githubusercontent.com/75422800/185997476-3e8c6392-be35-4af8-9066-e7a074feaaf7.mov
> Fix hamburger menu

- src/constants/index.ts
Went through the index file and noticed some of the PIDs dont follow the existing formats.
> Add any missing PIDs

- src/utils/thirdPartyIntegrations.ts
added condition to handle additional rewarder contracts for sperax
> add rewarder contract for arb frax usds metapool

- src/constants/index.ts
- src/hooks/useApproveAndDeposit.ts
- src/hooks/useWithdrawFormState.ts
- src/pages/Deposit.tsx
- src/pages/Withdraw.tsx
- src/providers/BasicPoolsProvider.tsx
- src/utils/index.ts
- `isMigrated` is not indicative of ABI type
- Remove `isLegacy` in favor of clearer `isGuarded` and `isWithdrawFee` which more closely aligns with ABI types
> Fix ABI selection, don't use isMigrated

- cypress.json
- cypress/integration/advancedOption.test.ts
- cypress/integration/deposit.test.ts
- cypress/integration/swap.test.ts
- cypress/integration/withdrawal.test.ts
- cypress/support/commands.ts
- src/hooks/usePoolData.ts
- src/pages/App.tsx
- src/pages/Deposit.tsx
Problems addressed:
- txns would fail with "deadline not met since" since the backend deployment does some timestamp fast forwarding
- `_Eip1193Bridge` export changed to `Eip1193Bridge`
- `react-query` dev popup blocks cypress interaction
- uncaught divide by zero
- `cy.react` is borked
- If we don't wait long enough, minichef will load and reload the tokens which clears existing inputs.
- element selection scrolls element to top of viewport
> Fix parts of CI

- src/components/AccountDetails.tsx
- src/components/Copy.tsx
> Fix breaking of change account text

- src/pages/CreatePool/CreatePoolDialog.tsx
- src/pages/CreatePool/index.tsx
- src/pages/Pools.tsx
CreateDialog needed falsy protection to stop type error from occurring.
Added chain logic to render create pool btn
> hide create pool btn, fix multiple tokens issue

- src/hooks/useRegistryAddress.ts
- src/utils/gauges.ts
Only execute this call when on Arbitrum or Optimism. Currently causing bug that prevents pages from rendering.
> Protec ChildGauge contract call against certain chains.

- src/providers/TokensProvider.tsx
The checkmark next to tokens on the Pools page should now meet the follow criteria:
1) All LP tokens of saddle-approved pools
2) All tokens on the uniswap list
3) All tokens in saddle-approved pools
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203194205336480
> Mark saddle-approved tokens as safe

- src/constants/index.ts
- src/hooks/useSwapStats.ts
Add token addresses for missing tokens
> Fix prices

- src/components/Toastify.tsx
- src/components/TokenClaimDialog.tsx
- src/hooks/useUserGauge.ts
- src/pages/Farm/ClaimRewardsDlg.tsx
- src/pages/Farm/StakeDialog.tsx
Adjust logic in the `TokenClaimDialog` to simply reuse the claim function from the `useUserGauge` hook.
> Fix gauge claiming

- src/components/MyShareCard.tsx
- src/pages/Swap/Swap.tsx
- src/utils/priceImpact.ts
> Link to L2D4 staking. Don't use USD price for swap price impact.

- src/pages/Farm/Farm.tsx
- src/pages/Farm/FarmOverview.tsx
- src/utils/gauges.ts
Hide outdated gauge from nonstaked users, display staked users option to withdraw
> First pass at fusdc unstaking

- src/components/TokenClaimDialog.tsx
hide since old rewards are invalid
> hide dead fUSDC gauge rewards
